{
  "os": "linux",
  "dist": "trusty",
  "sudo": false,
  "group": "stable",
  "addons": {
    "apt": {
      "packages": [
        "cmake",
        "ninja-build"
      ]
    }
  },
  "compiler": "gcc",
  "language": "c",
  "script": [
    "mkdir build",
    "cd build",
    "cmake ..",
    "cmake --build .",
    "cd test",
    "ctest --output-on-failure",
  ],
}
